package constants

const (
	RC_SUCCESS = "00"
	RD_SUCCESS = "Success"

	RC_INVALID_REQUEST_DATA = "02"
	RD_INVALID_REQUEST_DATA = "Invalid request data"

	RC_DATA_NOT_FOUND = "03"
	RD_DATA_NOT_FOUND = "Data not found"

	PAYMENT_METHOD_TUNAI    = 1
	PAYMENT_METHOD_TRANSFER = 2
	PAYMENT_METHOD_QRIS     = 3

	//0=pending 1=sukses 2=gagal
	PAYMENT_STATUS_PENDING = 0
	PAYMENT_STATUS_SUCCESS = 1
	PAYMENT_STATUS_GAGAL   = 2

	DELIVERY_METHOD_DINE_IN = 1
	DELIVERY_METHOD_PICKUP  = 2
	DELIVERY_METHOD_COURIER = 3

	DATE_TIME_FORMAT = "2006-01-02 15:04"
)

var (
	MODE_UNIT_TEST = false
)
