// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	model "setokoapp/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// ITOrder is an autogenerated mock type for the ITOrder type
type ITOrder struct {
	mock.Mock
}

// FindOrderDetails provides a mock function with given fields: orderId
func (_m *ITOrder) FindOrderDetails(orderId string) (model.OrderReceipt, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderDetails")
	}

	var r0 model.OrderReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.OrderReceipt, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(string) model.OrderReceipt); ok {
		r0 = rf(orderId)
	} else {
		r0 = ret.Get(0).(model.OrderReceipt)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITOrder creates a new instance of ITOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITOrder {
	mock := &ITOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
